// Code generated by "stringer -type Prior"; DO NOT EDIT.

package constant

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Super-255]
	_ = x[Admin-127]
	_ = x[Normal-63]
	_ = x[Visitor-1]
}

const (
	_Prior_name_0 = "Visitor"
	_Prior_name_1 = "Normal"
	_Prior_name_2 = "Admin"
	_Prior_name_3 = "Super"
)

func (i Prior) String() string {
	switch {
	case i == 1:
		return _Prior_name_0
	case i == 63:
		return _Prior_name_1
	case i == 127:
		return _Prior_name_2
	case i == 255:
		return _Prior_name_3
	default:
		return "Prior(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
